plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\morip\\LIVECREATE Dropbox\\森川卓典\\森川フォルダ\\cursor\\projects\\line-secretary-calendar"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]